import os
import tkinter as tk
from tkinter import filedialog, messagebox, ttk
from music21 import converter, instrument, metadata
import librosa
import soundfile as sf
import tempfile
import shutil
import glob

# Funzione per trascrivere file audio in MIDI
from basic_pitch.inference import predict_and_save

SUPPORTED_INSTRUMENTS = {
    "Pianoforte": instrument.Piano(),
    "Violino": instrument.Violin(),
    "Violoncello": instrument.Violoncello()
}

class Audio2ScoreApp:
    def __init__(self, master):
        self.master = master
        master.title("Audio2Score")
        master.geometry("500x400")

        self.frame = ttk.Frame(master)
        self.frame.pack(padx=10, pady=10, fill='both', expand=True)

        self.label = ttk.Label(self.frame, text="Trascina un file audio (.mp3, .wav)")
        self.label.pack(pady=10)

        self.drop_area = tk.Label(self.frame, text="⬇️ DROP FILE HERE ⬇️", relief="ridge", borderwidth=2, height=5)
        self.drop_area.pack(fill='x', padx=20, pady=10)
        self.drop_area.bind("<Button-1>", self.browse_file)

        self.instrument_label = ttk.Label(self.frame, text="Strumento:")
        self.instrument_label.pack()
        self.instrument_choice = ttk.Combobox(self.frame, values=list(SUPPORTED_INSTRUMENTS.keys()))
        self.instrument_choice.set("Pianoforte")
        self.instrument_choice.pack(pady=5)

        self.btn_convert = ttk.Button(self.frame, text="Converti in Spartito", command=self.process_audio)
        self.btn_convert.pack(pady=20)

        self.status = ttk.Label(self.frame, text="Stato: pronto", relief="sunken", anchor='w')
        self.status.pack(fill='x', side='bottom')

    def browse_file(self, event=None):
        file_path = filedialog.askopenfilename(filetypes=[("Audio Files", "*.mp3 *.wav")])
        if file_path:
            self.convert_file(file_path)

    def convert_file(self, file_path):
        """Process the selected audio file and convert it to a musical score"""
        if not file_path:
            return
        try:
            self.status.config(text="Analisi in corso...")
            self.master.update()
            midi_path, musicxml_path, pdf_path, png_path = self.audio_to_score(file_path)

            result_msg = f"Spartito generato con successo!\n\n"
            result_msg += f"MIDI: {midi_path}\n"
            result_msg += f"MusicXML: {musicxml_path}\n"
            if pdf_path:
                result_msg += f"PDF: {pdf_path}\n"
            if png_path:
                result_msg += f"PNG: {png_path}\n"

            messagebox.showinfo("Fatto!", result_msg)
            self.status.config(text="Fatto! Spartito generato")
        except Exception as e:
            messagebox.showerror("Errore", f"Si è verificato un errore:\n{str(e)}")
            self.status.config(text=f"Errore: {str(e)}")

    def process_audio(self):
        file_path = filedialog.askopenfilename(title="Seleziona file audio", filetypes=[("Audio Files", "*.mp3 *.wav")])
        if file_path:
            self.convert_file(file_path)

    def audio_to_score(self, audio_path):
        """Convert audio file to musical score in multiple formats"""
        temp_dir = tempfile.mkdtemp()
        try:
            # Step 1: Load and convert audio to WAV format
            self.status.config(text="Caricamento audio...")
            self.master.update()
            wav_path = os.path.join(temp_dir, "input.wav")
            y, sr = librosa.load(audio_path, sr=16000)
            sf.write(wav_path, y, sr)

            # Step 2: Transcribe audio to MIDI using basic_pitch ML model
            self.status.config(text="Trascrizione audio in MIDI...")
            self.master.update()
            predict_and_save(
                [wav_path],
                output_directory=temp_dir,
                save_midi=True,
                save_model_outputs=False,
                sonify_midi=False
            )

            # Step 3: Find the generated MIDI file (basic_pitch uses pattern: input_basic_pitch.mid)
            midi_files = glob.glob(os.path.join(temp_dir, "*_basic_pitch.mid"))
            if not midi_files:
                raise FileNotFoundError("MIDI file not generated by basic_pitch")
            midi_path_temp = midi_files[0]

            # Step 4: Parse MIDI and create musical score
            self.status.config(text="Generazione spartito...")
            self.master.update()
            score = converter.parse(midi_path_temp)

            # Step 5: Set the chosen instrument
            chosen_instrument = SUPPORTED_INSTRUMENTS[self.instrument_choice.get()]
            for part in score.parts:
                part.insert(0, chosen_instrument)

            # Step 6: Add metadata
            if not score.metadata:
                score.metadata = metadata.Metadata()
            score.metadata.title = "Spartito generato da Audio2Score"

            # Step 7: Save output files
            output_base = os.path.abspath("spartito_output")
            midi_path = output_base + ".mid"
            musicxml_path = output_base + ".musicxml"

            # Save MIDI file
            score.write('midi', fp=midi_path)

            # Save MusicXML file (standard format, always works)
            score.write('musicxml', fp=musicxml_path)

            # Try to save PDF (requires MuseScore)
            pdf_path = None
            try:
                self.status.config(text="Generazione PDF...")
                self.master.update()
                pdf_path = output_base + ".pdf"
                score.write('musicxml.pdf', fp=pdf_path)
            except Exception as e:
                print(f"Warning: Could not generate PDF: {e}")
                print("MuseScore might not be installed or configured")

            # Try to save PNG (requires LilyPond)
            png_path = None
            try:
                self.status.config(text="Generazione PNG...")
                self.master.update()
                png_path = output_base + ".png"
                score.write('lily.png', fp=png_path)
            except Exception as e:
                print(f"Warning: Could not generate PNG: {e}")
                print("LilyPond might not be installed or configured")

            return midi_path, musicxml_path, pdf_path, png_path

        finally:
            # Clean up temporary directory
            try:
                shutil.rmtree(temp_dir)
            except Exception as e:
                print(f"Warning: Could not clean up temp directory: {e}")

if __name__ == '__main__':
    root = tk.Tk()
    app = Audio2ScoreApp(root)
    root.mainloop()
